name: trivy-scanning

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: "30 09 * * 1"

permissions:
  actions: read
  contents: read
  security-events: write

jobs:
  trivy-scanning-job:
    name: Trivy Security Scanning Job
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Run Trivy vulnerability scanning image webspellchecker/wproofreader
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: "webspellchecker/wproofreader:latest"
          scan-type: "image"
          format: "sarif"
          output: "trivy-results.sarif"
          vuln-type: "os,library"
          severity: "CRITICAL,HIGH"

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: "trivy-results.sarif"
          category: image-scan